stages:
  - kics_test
  - install_open5gs
  - install_ueransim
  - smoke_test # add smoke test

kics_scan:
  tags: 
    - gitlab-org
  stage: kics_test
  allow_failure: true
  script:
    - helm template open5gs openverso/open5gs --values open5gs_values.yml > open5gs.yaml
    - curl -sfL 'https://raw.githubusercontent.com/Checkmarx/kics/master/install.sh' | bash
    - kics scan -t Kubernetes open5gs.yaml | tee security-scan.txt
  artifacts:
    paths: 
      - ./security-scan.txt
      
install_open5gs:
  image: alpine/helm
  stage: install_open5gs
  script:
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm install openverso/open5gs --values open5gs_values.yml
  
install_ueransim:
  image: alpine/helm
  stage: install_ueransim
  script: 
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm install ueransim-gnb openverso/ueransim-gnb --values cntf/open5gs/application/openverso_ueransim_gnb_values.yml #added paths to created helm values files
    - helm install ueransim-ues openverso/ueransim-ues --values cntf/open5gs/application/openverso_ueransim_ues_values.yml

smoke_test: # added smoke test that pings www.google.com
  image: ubuntu:latest
  stage: smoke_test
  script:
    - sh cntf/open5gs/application/ueransim_smoke_test.sh