variables:
  TF_ROOT: open5gs/infrastructure/eks
  TF_STATE_NAME: open5gs

include:
  - template: Terraform/Base.gitlab-ci.yml  
  - template: Jobs/SAST-IaC.gitlab-ci.yml   

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup 
  - kics_test
  - install_open5gs
  - install_ueransim
  - smoke_test 

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build
  environment:
    name: $TF_STATE_NAME
    action: prepare

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start

cleanup:
  extends: .terraform:destroy
  dependencies:
    - deploy
  environment:
    name: $TF_STATE_NAME
    action: stop
  when: manual

kics_scan:
  image: ubuntu:latest
  stage: kics_test
  allow_failure: true
  script:
    - apt-get update && apt-get install -y curl
    - curl -sfL 'https://raw.githubusercontent.com/Checkmarx/kics/master/install.sh' | bash
    - helm template open5gs openverso/open5gs --values open5gs_values.yml > open5gs.yaml
    - kics scan -t Kubernetes open5gs.yaml | tee security-scan.txt
  artifacts:
    paths: 
      - security-scan.txt
      
install_open5gs:
  image:
    name: alpine/helm
    entrypoint: [""]
  stage: install_open5gs
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  environment:
    name: open5gs_cluster 
  script:
    - apk add --no-cache bash
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - aws eks update-kubectl --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm install open5gs openverso/open5gs --values ./open5gs_values.yml

install_ueransim:
  image: alpine/helm
  stage: install_ueransim
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  environment:
    name: open5gs_cluster 
  script: 
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - aws eks update-kubectl --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm install ueransim-gnb openverso/ueransim-gnb --values ./openverso_ueransim_gnb_values.yml #added paths to created helm values files
    - helm install ueransim-ues openverso/ueransim-ues --values ./openverso_ueransim_ues_values.yml

smoke_test:
  image: ubuntu:latest
  stage: smoke_test
  environment:
    name: open5gs_cluster 
  script:
    - apt-get update && apt-get install -y curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - sh ./ueransim_smoke_test.sh